<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kd_base"
 *
 * Auto generated by Extension Builder 2015-01-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backend User Notes',
	'description' => 'This extension provides an extension to the sys_note records and their functionality accross the TYPO3 backend. It provides a toolbar item that shows unread notes and a module to create and send notes to other users',
	'category' => 'plugin',
	'author' => 'Kevin Ditscheid',
	'author_email' => 'kevinditscheid@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => 'alpha1',
	'constraints' => array(
		'depends' => array(
            'backend' => '7.6.0 - 8.7.99',
            'core' => '7.6.0 - 8.7.99',
            'lang' => '7.6.0 - 8.7.99',
            'sys_note' => '7.6.0 - 8.7.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);